version: '3.8'

services:
  web:
    build: ./bookmarks
    # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
    volumes:
      - ./bookmarks/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis
    command: redis-server
    expose:
      - '6379'
    ports:
      - '127.0.0.1:6379:6379/tcp'
    hostname: localhost
    volumes: 
      - redisdata:/data
    


volumes:
  postgres_data:
  redisdata:

