version: '3.8'

services:
  web:
    build: ./bookmarks
    # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
    volumes:
      - ./bookmarks/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - app-tier
      - live
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - live
  
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier
    
volumes:
  postgres_data:

networks:
  app-tier:
    driver: bridge
  live: